- hub: 💬 Lobby┆┆1 💬
  info: ''
  can_gm: true
  music_ref: Dev
  single_cm: true
  hide_client: false 
  areas:
  - area: 💬 Lobby┆┆1 💬
    background: ddlobby
    bglock: true
    evidence_mod: Mods
    showname_changes_allowed: true
    locking_allowed: false
    iniswap_allowed: true
    basement: false
    can_cm: false
    can_change_status: false
    desc: '==============================
           Per vedere le sale fare /hub  
           Per cambiare sala fare /hub ID
           =============================='
- hub: 💬 Lobby┆┆2 💬
  info: ''
  can_gm: false
  music_ref: Dev
  single_cm: true
  hide_client: false 
  areas:
  - area: 💬 Lobby┆┆2 💬
    background: ddlobby
    bglock: true
    evidence_mod: Mods
    showname_changes_allowed: true
    locking_allowed: false
    iniswap_allowed: true
    basement: false
    can_cm: false
    can_change_status: false
    desc: '==============================
           Per vedere le sale fare /hub  
           Per cambiare sala fare /hub ID
           =============================='
  - area: 💬 Lobby┆┆ 💬
    background: ddlobby
    bglock: true
    evidence_mod: Mods
    showname_changes_allowed: true
    locking_allowed: false
    iniswap_allowed: true
    basement: false
    can_cm: true
    can_change_status: false
    desc: '==============================
           Per vedere le sale fare /hub  
           Per cambiare sala fare /hub ID
           =============================='
- hub: 💬 Lobby┆┆3 💬
  info: ''
  can_gm: false
  music_ref: Dev
  single_cm: true
  hide_client: false 
  areas:
  - area: 💬 Lobby┆┆3 💬
    background: ddlobby
    bglock: true
    evidence_mod: Mods
    showname_changes_allowed: true
    locking_allowed: false
    iniswap_allowed: true
    basement: false
    can_cm: false
    can_change_status: false
    desc: '==============================
           Per vedere le sale fare /hub  
           Per cambiare sala fare /hub ID
           =============================='
- hub: 💬 Lobby┆┆4 💬
  info: ''
  can_gm: false
  music_ref: Dev
  single_cm: true
  hide_client: false 
  areas:
  - area: 💬 Lobby┆┆4 💬
    background: ddlobby
    bglock: true
    evidence_mod: Mods
    showname_changes_allowed: true
    locking_allowed: false
    iniswap_allowed: true
    basement: false
    can_cm: false
    can_change_status: false
    desc: '==============================
           Per vedere le sale fare /hub  
           Per cambiare sala fare /hub ID
           =============================='



# Default options
# - hub: Main
#   abbreviation: M
#   move_delay: 0
#   arup_enabled: true
#   hide_clients: false
#   info: ''
#   can_gm: true
#   music_ref: ''
#   client_music: true
#   max_areas: 50
#   single_cm: false
#   censor_ic: true
#   censor_ooc: true
#   areas:
#   - area: Basement
#     background: default
#     pos_lock: none
#     bg_lock: false
#     evidence_mod: FFA
#     can_cm: true
#     locking_allowed: false
#     iniswap_allowed: true
#     showname_changes_allowed: true
#     shouts_allowed: true
#     jukebox: false
#     abbreviation: B
#     non_int_pres_only: false
#     is_locked: FREE
#     blankposting_allowed: true
#     hp_def: 10
#     hp_pro: 10
#     doc: no document.
#     status: IDLE
#     move_delay: 0
#     hide_clients: false
#     max_players: -1
#     desc: ''
#     music_ref: ''
#     client_music: true
#     replace_music: false
#     ambience: ''
#     can_dj: true
#     hidden: false
#     can_whisper: true
#     can_wtce: true
#     music_autoplay: false
#     can_change_status: true
#     use_backgrounds_yaml: false