- Ace Attorney:
    - AADetentionCenter
    - AALobby
    - AJDetentionCenter
    - AJLobby
    - AcroRoomJFA
    - AirportJFA
    - AlbaOfficeAAI
    - Anime
    - ArtRoom
    - AtmeyOfficeTT
    - AuraLab
    - BackstageAJ
    - BakerStreet
    - BakerStreetFlat
    - BandoLandAAI
    - BaroksOffice
    - BerryBigCircusAAI2
    - BerryBigCircusJFA
    - Birthday
    - BlueScreensTT
    - BluecorpAA
    - BorschtBeltClubAJ
    - CargoHoldAAI
    - Christmas
    - CochenOfficeAAI
    - CoronerOffice
    - CountyCourt
    - CruiseCourt
    - DDDetentionCenter
    - DDLobby
    - DGSEnglishCourt
    - DGSHotel
    - DGSJapanCourt
    - Default
    - DeLiteHouseTT
    - DetentionCenterAAI2
    - DogenCellAAI2
    - DrewStudioAJ
    - DualDestinies
    - EdgeworthOfficeAA
    - EdgeworthOfficeAAI
    - EmbassyAAI
    - EngardeManorJFA
    - EnglishCourt
    - FilmSetAAI2
    - GS4Night
    - GantOfficeAA
    - Gaol
    - GetwaterHotelJFA
    - GetwaterStageJFA
    - GlobalStudiosIndoorsAA
    - GlobalStudiosOutdoorsAA
    - GourdLakeAA
    - GreatWitchtrialCourt
    - GrossbergOfficeAA
    - gs4
    - HD
    - HazakuraTemple1TT
    - HazakuraTemple2TT
    - HickfieldClinicAJ
    - HospitalRoomDGS
    - HotelRoomAA
    - HottiClinicJFA
    - InsidePlaneAAI2
    - Khura'in
    - KhurainDetentionCenter
    - KlavierOfficeAJ
    - KurainVillageJFA
    - LobbyAPZ
    - LobbyDGS-ENG
    - LobbyDGS-JAP
    - LobbySOJ
    - LockerRoom
    - LogicChessAAI2
    - MASONAJ
    - MansionAAI2
    - MeraktisClinicAJ
    - MoeRoomJFA
    - MuseumAAI2
    - MuseumTT
    - NewCourt
    - OfficeNightAA
    - OfficeWright
    - OfficeWrightAJ
    - OutsideCourthouseAnime
    - OutsidePhoenixOfficeAnime
    - OutsidePhoenixOfficeAnimeNight
    - OutsidePlaneAAI2
    - OutsidePoliceStationAnime
    - PICAAI2
    - ParkingLotAA
    - PeopleParkAJ
    - PerceiveAJ
    - PerceiveDD
    - PhoenixOfficeAA
    - PhoenixOfficeAnime
    - PlaneAAI
    - PlaneLoungeAAI
    - PlaneLoungeLandAAI
    - PrecinctAA
    - PrisonAAI2
    - PrisonCellAJ
    - PrisonCourtyardAAI2
    - RooftopAAI2
    - RuinedCourt
    - SecretRoomsJFA
    - SecurityCompanyTT
    - ShipAAI2
    - Sky
    - SpaceCourt 
    - StageAAI
    - StageDisassembledAAI
    - SunshineColiseumAJ
    - TenderLenderTT
    - Themis
    - TouhouCourt
    - TrainstationAA
    - TrainstationNight
    - TresBienTT
    - WaitingRoomAAI
    - WestAAI
    - WinterPalaceAAI2
    - WitchTrialCourt
    - VitaminSquareTT
    - VortexOffice
- Black Survival:
    - BSLumiaisland
    - BSLumiaislandnight
    - BSLumiaislandoriginal
    - BSSeoulruins
- Fate:
    - FSNEmiyaDojo
    - FSNFuyukiBridge
    - FSNFuyukiChurch
    - FSNMiyamaPlayground
    - FSNShintoCityCenter
    - Garden of Avalon
    - UnlimitedBladeWorks
- Higurashi:
    - higurashiangelmortday
    - higurashiangelmortnight
    - higurashihinamizawaday
    - higurashihinamizawanight
    - higurashihinamizawanoon
    - higurashimaebaraday
    - higurashimaebaranight
    - higurashimaebaranoon
    - higurashiokinomiyaday
    - higurashiokinomiyapool
    - higurashischoolday
    - higurashischoolnight
    - higurashitimevoid
- Homestuck:
    - hsfalternia1
    - hsfalternia2
    - hsfclownfest
    - hsfrooms
- Omori:
    - omoriSpace
    - omoriblackspace
    - omoriwhitespace
- Persona:
    - ShadowWorld
    - MidnightChannel
    - P3VelvetRoom
    - P4VelvetLimo
    - TartarusEntrance
- Professor Layton:
    - CVFerrisWheelPark
    - CVFerrisWheelPark2
    - CVIndoors
    - CVIndoors2
    - CVMiscellaneous
    - CVReinholdManor
    - CVReinholdManor2
    - CVSewers
    - CVStMystere
    - CVStMystere2
    - CVStMystere3
    - CVStMystere4
    - CVStMystereNight
    - CVStMystereNight2
    - CVTower
    - CVTower2
    - CVTower3
    - CVUnderground
    - lobbyPLvsAA-ENG
    - lobbyPLvsAA-LAB
    - PlvsAAcastle
- Steins;Gate:
    - Akihabara
    - Shibuya
    - Shibuya2
    - Shrine
    - Lab
    - Radiobuilding
- The Immorals:
    - theimmoralsentrance
    - theimmoralshall2
    - theimmoralskatoriroom
    - theimmoralslivingroom
    - theimmoralslivingroom2
    - theimmoralsmisoraroom
    - theimmoralsoffice
    - theimmoralsstoreroom
    - theimmoralssumireroom
- Umineko:
    - UminekoForest
    - UminekoGarden
    - UminekoGoldenLand
    - UminekoGuestHouse
    - UminekoGuestHouseDark
    - UminekoMansionDay
    - UminekoMansionNight
    - UminekoWedding
- Zero Escape:
    - 9991stClassCabinA
    - 9991stClassCabinB
    - 9992ndClassCabin
    - 999Apartment
    - 999CaptainsQuarters
    - 999Cargo
    - 999Casino
    - 999Cdeck
    - 999CentralStairs
    - 999Chapel
    - 999Chart
    - 999Confinement
    - 999DoorsA
    - 999DoorsB
    - 999Hospital
    - 999Kitchen
    - 999Library
    - 999Operating
    - 999Shower
    - 999Steam
    - 999Steeldoor
    - 999Study
    - 999Torture
- Altro:
    - AggretsukoKaraoke
    - AggretsukoOffice
    - ArmandoTennis
    - BaseLancio
    - BaseballField
    - Blackout
    - CHSchool
    - CafeRembrandt
    - Casino
    - City
    - CoffeeShop
    - Colosseo
    - CompanyLounge
    - Custom
    - DR2Park
    - Downtown
    - Duomodimilano
    - FNF CreepySchool
    - FNF CreepySchool
    - ForestainFiamme
    - Gilded7Casino
    - Giygas
    - Headquarters
    - HelicopterInside
    - Howl's Castle
    - InterrogationRoom
    - InterviewRoom
    - JapaneseHall
    - JapaneseRoom
    - JunesShadow
    - Kitchen
    - Laboratory
    - LivingRoom
    - Luna
    - MayQueen
    - MayoMart
    - MeetingRoom
    - MeetingRoomClosed
    - Miyazakiworld
    - NightClub
    - Psichedelico
    - PsycheLocks
    - Quindecim
    - Road
    - RuinedGate
    - SchoolHall
    - SchoolRooftop
    - SoccerField
    - Stairs
    - Stars
    - Statua della libertà
    - StripClub
    - SurveillanceRoom
    - Tent
    - Terre Selvagge
    - TrainInStation
    - TrainStation
    - Underground
    - VRRoom
    - VillageRoad
    - Villaggio Medievale
    - WarframeFortuna
    - YTTDCourtroom
    - YTTDMainGame
    - alefgard
    - andri's lab
    - apotos
    - bbsnowtown
    - beach
    - cvstmystere
    - dave's house
    - ddlc
    - ddlchomes
    - favijsgabuzzino
    - forest
    - hotsprings
    - housedark
    - houselight
    - htf
    - libraryofruinamerged
    - nobg
    - ocarcade
    - whiteout
