- Conan Edogawa
- Jezail
- Layton Winter
- Max
- Gonta
- Sailor
- Trucy
- BlackquillSOJ
- Bonny de Famme
- Gundham
- Weiss
- Kagero (FEFatesHD)
- Jing Ke
- Cicciogamer89
- Zak
- Q-Taro
- Disciple
- Ashe (3H)
- Kyojuro GBF
- Charles
- Lauren Paups
- Thomas
- Crogrey
- Ben
- Es
- Neopolitan
- Claus
- Portsman
- Hosonaga
- Tenko
- Keiji 
- Yuki
- Gumshoe
- Cenobia
- Oldbag
- Matt
- Yasuhiro
- Hiyoko
- Mae
- Barnham
- Yuujin Mikotoba
- Byakuya
- MisuzuRCG
- Kazuma
- Paul Atishon
- Ranger
- Godot
- Inosuke GBF
- ApolloPro
- ChefRCG
- Junko
- Sebastian
- Shinobu GBF
- Bucky
- Snow
- Di-Jun Huang
- Bonnie_Karin
- Lucina (Awakening)
- Kai
- Ridelle
- Hans Adult
- EdgeworthHD
- Luka
- Ema
- Dave Strider
- Gilgamesh FGO
- Juniper
- Robin (M) (Awakening)
- Karuta Uruwashi (AyakashiAkashi)
- Goro Majima (Y0)
- Retinz
- Fawles
- Ini
- Octopath Traveler
- Hugh
- Byrne
- WillP
- Jin
- DreamHero_OMORI
- Phoenix
- April
- PsycheLocks
- Sorin
- Rayfa
- Rokuro Yamaguchi (AyakashiAkashi)
- Matsuda
- Makoto
- Layton
- Romani FGO
- Palutena (HD) (Uprising)
- Sakura
- Beppo
- Judge GB 
- Peko
- Hayasaka
- Berkut (Echoes)
- Professor Guedes
- Kazuichi
- Labrys
- Kanji
- Korekiyo
- Hifumi
- Quercus Alba
- Roylott
- Mahiru
- JudgeKhura'in
- Moeka
- Rottytops
- Angie
- RikiRCG
- Vortex Judge
- Clover VLR
- LanaP
- Rhoda Teneiro
- Diego
- Felix White
- Bolo
- CC
- Robin Hood FGO
- Bolo (SevenSirens)
- Hanekoma FRx
- Shiki FRx
- Mayuri
- Furio
- Orla
- Reines
- Justin
- Azazel
- Kaito
- Kira
- Trucy SOJ
- Espella
- Sherlock FGO
- Ia Shishibe (AyakashiAkashi)
- Apollo
- Gina
- Joe
- Kurisu
- Zero Manzanka (AyakashiAkashi)
- Riskyboots
- Dimitri (3H)
- Parker
- Justice
- Elise
- Klavier Young
- Ranmaru
- Bailiff
- Pit (HD) (Uprising)
- Death the Kid
- Manfred
- BurnovRCG
- Ranpo Edogawa
- Hazama
- Mario
- Juzo megure
- Ron
- Crab
- Tenma 
- Okita Souji (Alter)
- Rhea (3H)
- Giyu GBF
- Corrin (F) (Fates)
- KaoriRCG
- Adachi
- Kiibo
- Judge's Bro
- Claire
- Grey
- Cammy
- Haori
- LarryIK
- Sasha
- Long Lang
- Shido
- KilluaZoldyck_DR
- HoboPhoenix
- Smiles
- Gardevoir
- John Marsh
- Saki
- HibariRCG
- Hilda
- Judge
- Inga
- Layton Young
- Necos
- White
- Butch Browning
- Mashu Kyrielight
- Nakabachi
- Shiv
- Inoob
- Squidsmith (SevenSirens)
- Viridi (HD) (Uprising)
- Payne Train v2
- Treat
- Mutantheart
- Jay Elbird
- MihokoRCG
- ZeroAPZ
- Gerry Scotti
- MorganaP5
- Haida
- Shinichi Kudo
- Gilgamesh(Child) FGO
- John Egbert
- Suzuha
- Ponco
- Watanabe You
- Trucy Young
- Leon
- SkullmageddonRCG
- Peppe Vessicchio
- Jinxie
- Anton
- Mikan
- ApolloSOJ
- Maya
- Okabe
- Auchi
- John Garrideb
- Gotts
- De Killer
- Kronya (3H)
- Penny
- Pandemonica
- Franken Stein
- Ichigo
- Monaca
- Meekins
- AthenaSOJ
- Grossberg Old
- Shantae
- Empresssiren (SevenSirens)
- Matilda
- Nao
- AboboRCG
- Knightley
- Reko
- Trucy Pro
- Vera
- Decargo
- Angel Starr
- Chidouin
- Rindo NTy
- Plink (SevenSirens)
- Klavier DD pro
- Emmy
- Clover
- Nine The Phantom
- Colias Palaeno
- Mai
- Yu
- Mitsuru
- William
- Patrick
- Ibuki
- Ran Mouri
- Lara Triton
- Mia
- DrHotti
- Pizzard
- Asougi
- Gengar
- Jade Harley
- Manfred Evil
- Bikini
- Yew
- Payne SOJ
- Alm (Echoes)
- Beatrice
- Drew
- Lisa
- Yanni
- Uzuki FRx
- Altamont
- Tyrell Badd
- Venus
- Tenmyouji
- Paper Mario
- Battle
- K
- Komaru
- Dane Gustavia
- Prove
- Rozaic
- Guy
- Kay 
- Barghest (S3)
- Akihiko
- Twogami
- Rottytops (SevenSirens)
- NarratorDGS
- Flayn (3H)
- Bailiff JP
- Newman
- Mayakid
- Nekomaru
- Orca
- Gabibbo
- Cyanea
- Shinjiro Aragaki
- Ryoma
- Safalin
- Yotobi
- L
- ConciergeRCG
- Teruteru
- YamadaRCG
- Mafuyu Asahina
- Barok
- Aigis
- Olga Marie
- Seishirou
- MamiRCG
- Nero Claudius
- Zinc Lablanc
- Hajime
- Betty de Famme
- Tahrust
- Ahlbi
- Darklaw
- PearlSOJ
- Kudo
- Gashu
- Gant
- Lamiroir
- Lotta
- Zenitsu GBF
- Grete
- Mitsuki FRx
- Oscar Fairplay Juror
- Monokuma
- Robin (F) (Awakening)
- Sayaka
- Azura (Fates)
- Yuri
- Phi
- Tina Etuprika (AyakashiAkashi)
- Joshua FRx
- Chie
- Dhurke D
- Datz
- Phoenix hobo def
- Rachel Alucard
- Megumi
- Ernest Amano
- joker (p5gb)
- Sunny (omori)
- EmaSOJ
- Mike
- MayaSOJ
- Donnabella
- Andistandhin
- Platinum The Trinity
- Kagari
- Hinako
- Vasquez
- Himiko
- Santa
- Hazama (Pink)
- Plum Kitaki
- Alita Tiala
- YakuzaRCG
- Nikomina 
- Wocky Kitaki
- Tanjiro GBF
- Iris
- Roscoe
- Sal
- Dimitri
- Neku
- Kiryu Moeka
- Alice
- Shih-na
- Cody
- Zach
- Sky (SevenSirens)
- Sothis (3H)
- Layton Inquisitor
- KenjiRCG
- Blake Belladonna
- Monica (3H)
- Camilla (FE)
- MilesSOJ
- Dahlia
- Geiru
- Matilda Headset
- Maho
- Archer
- Nana
- Marshall
- Kristoph
- Sou
- Garan
- Megundal
- Kaede
- Teddie
- Megumin
- JudgeCalifornia
- Simon
- Winfred Kitaki
- Chihiro
- Maggey
- Bernadetta (3H)
- Sara
- Cerberus
- Ted
- Makepeace
- Mysterious Heroine X FGO
- Kirigiri
- Deplume
- Stroganov
- Layton Evil
- KyokoRCG
- Merlin
- Maki
- ApolloDD Wit
- Coco Atarashi FRx
- Starbuck
- EmaAJ
- Aigis (Godot)
- Toko
- Seteth (3H)
- Okita Souji
- Ishimaru
- Zero
- Loremaster
- Derek Stilles
- Yukari
- Enju Yoinara (AyakashiAkashi)
- Marlon Rimes 
- Lance Amano
- Kanna
- Lelouch
- Naegi
- Klavier
- Goodman
- MilesKid
- Franziska
- Acro
- Snake
- Miu
- Akane
- Fuyuhiko
- Naoto
- Ryuunosuke
- Male_tsumugi
- Tully Tinpillar
- ShoMinamimoto FRx
- Pearl
- Sho Minazuki
- Susato
- Don
- Sig
- Larry
- Oscar Fairplay
- Naki Kokuriko (AyakashiAkashi)
- Lbelle
- Clive
- Nagi NTy
- Sesena Kanou (AyakashiAkashi)
- Megumi FRx
- Nezuko GBF
- Josephine
- Coco NTy
- YokoRCG
- Anzu
- Sithe
- Delicia
- Mordred
- Sherlock
- Marie
- Margaret
- Elizabeth
- Kashima Akebono (AyakashiAkashi)
- Yosuke
- Daryan Crescend
- Alice VLR
- Gudako
- SupportReaper
- Fantozzi
- Vinnie
- Polly
- Kokichi
- Zdrada
- Chrom (Awakening)
- Fishazama
- Mila (Echoes)
- Grima (FEH)
- Sonia
- Gin
- Daru
- Judge GK2
- Bowl
- Maria
- Waver Velvet
- Pierce
- Linhardt (3H)
- Raymond
- Samekichi
- Mishima
- Rise
- Gregory AAI
- Zapple (SevenSirens)
- PhoenixHD
- Kingdom Hearts
- Dio
- Postal Dude
- Narrator
- NoizeRCG
- Jubei
- Byleth (F) (3H)
- Ninthman
- MisakoRCG
- Wesley Stickler
- Valant
- Mysterious Heroine X (Alter) FGO
- Ishtar (Rider)
- Byleth (M) (3H)
- Lotus
- Rhyme FRx
- James Moriarty
- Favij
- Mamemomi
- Seven
- Yuuki Terumi
- Asahina
- Sahwit
- Bailiff GB
- Shuji Ikutsuki
- Blackquill
- Desiree
- Joan
- Wellington
- Cindy
- Bellboy
- Edelgard (3H)
- Ibuki Mioda Alternative
- Nae
- Descole
- Goldie
- Celica A Mercury
- Dobinbough
- Riskyboots (SevenSirens)
- Fulbright
- Vincent Brooks
- JokerP5
- Alice (yttdbeta)
- BB
- Quark
- Lana
- KunioRCG
- Corrin (M) (Fates)
- Filch
- Adrian
- Harmony (SevenSirens)
- Iris Watson
- Rinea (Echoes)
- Sarge
- Tsumugi
- Celica (Echoes)
- Machi Tobaye 
- Sonohigurashi
- Touko
- Neil
- Nemmy Tinpillar
- SabukoRCG
- Patricia
- The Batter
- Sirhan Dogen
- Scuttlebutt
- Shantae (SevenSirens)
- Dhurke
- Nagito
- Luke
- Rumba
- Alfendi
- Olga orly
- Saber
- Grosky
- Katrielle layton
- Luna
- Haito Minai (AyakashiAkashi)
- Moe
- The King
- Morgan
- Ellen
- Riku Takasou (AyakashiAkashi)
- Hutch Windibank
- Olivia
- Faris
- HiroshiRCG
- Brisbane
- Rufus
- Ace
- Atmey
- Justine Courtney
- Re-l Mayer
- Kotoko
- Aubrey (omori)
- Everyday
- Mia Young
- Zhuge Liang
- Chelmey
- Drebber
- HasebeRCG
- Means
- Laytonp
- Lobstersiren (SevenSirens)
- Judgement
- Ryuutarou
- Sakihata Rimi
- Tobias Gregson
- Nobunaga
- Sora
- LeTouse
- GodaiRCG
- PhoenixSOJ
- Ena_HD
- Taiga (Toradora)
- Uendo
- Nicole Swift
- Amara
- Chris
- Malina
- Dio brando vn
- Kokoro
- NaritakaRCG
- Souseki
- Yang
- Spark
- Modeus
- Regina
- Sky
- Vera (SevenSirens)
- Viola
- Claude (3H)
- Armie
- Vortex
- Beat FRx
- Lucy
- Ken
- O'Malley
- Shoka NTy
- Rem ReZero
- Beelzebub
- Nahyuta
- Celestia
- Kugie
- Yodai FRx
- Rantaro
- Richard
- MrHat
- Payne Max
- ButzSOJ
- Ruby Rose
- Naoto Kurogane
- Kariya
- Armstrong
- Vulper
- Senji Muramasa
- Flora
- Basilio (Awakening)
- Jeffrey Master
- Yuugo
- Viridian
- AsougiPro
- Dmitri
- Midori
- Behleeb
- Shuichi
- MayaPLvsAA
- Uzukumaru
- Phoenix Young
- Katherine Hall
- June
- Lucifer
- Blaise Debeste
- Miley
- Miles
- EmaAAI
- Jeanne D'Arc
- Lopunny
- Kurumada
- Kirumi
- Caster
- Aura
- Maurice
- Zangetsu (bleach)
- Yukiko
- Chiaki
- kadoc zemlupus fgo

