[tox]
envlist = py311
requires =
    tox>=4
    tox-uv>=1
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
package = skip
dependency_groups = dev
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest -q
